ALTER TABLE CONTENTREVIEW_ITEM ADD COLUMN urlAccessed bool NOT NULL default false;
ALTER TABLE CONTENTREVIEW_ITEM ADD COLUMN submissionId VARCHAR(255);
ALTER TABLE CONTENTREVIEW_ITEM ADD COLUMN resubmission bool NOT NULL default false;
ALTER TABLE CONTENTREVIEW_ITEM ADD COLUMN externalGrade VARCHAR(255);